LICENSE.txt

Resolves issue #19 and copyrights under "Cardinality Contributors"
Starting this PR to get the discussion going. Happy to change to a different license if needed.

Create MIT License file

---

smallboard/templates/base.html

Username only:
First-name + last-name:

Display first-name last-name rather than username when available

---

puzzles/templates/puzzles_table.html

Enable filtering by meta

---

puzzles/templates/puzzles_table.html
puzzles/urls.py
puzzles/views.py

Add puzzle deletion functionality

---

answers/templates/queue.html
hunts/templates/all_puzzles.html
hunts/views.py
puzzles/templates/puzzles_table.html

This fixes https://github.com/cardinalitypuzzles/smallboard/issues/27.

UI fix for issue 27

---

puzzles/__init__.py
puzzles/apps.py
puzzles/models.py
puzzles/signals/handlers.py
smallboard/settings.py

- Moved all the signal hooks from puzzles models.py to signals/handlers.py
- Fixed bug where meta puzzle did not get tagged itself on creation

Signal refactor

---

puzzles/templates/puzzles_table.html

Support filtering by tags

---

hunts/templates/tools.html
hunts/urls.py
hunts/views.py
smallboard/templates/base.html

very rough initial version for #4

add tools page

---

puzzles/templates/puzzles_table.html
puzzles/templates/title.html

Fix meta search

---

puzzles/puzzle_tree.py
puzzles/templatetags/puzzle_extras.py
puzzles/tests.py

Fix puzzle sorting bug

---

puzzles/tests.py

meta <=> tag tests

---

puzzles/forms.py
puzzles/templates/modals/set_meta.html
puzzles/templates/puzzles_table.html
puzzles/templatetags/puzzle_extras.py
puzzles/urls.py
puzzles/views.py
smallboard/templates/base.html

Option 2 for #84. make server call whenever "set meta" button is pressed for the form.

server call to avoid modal params

---

google_drive_lib/google_drive_client.py
smallboard/settings.py

See #91 for details. My friend was able to log in after I added his lowercased email to the whitelist.

Add lowercased emails to email whitelist (#91)

---

.circleci/config.yml
.env.test
README.md
manage.py
smallboard/settings.py

You can see our CircleCI status here: https://circleci.com/gh/cardinalitypuzzles/smallboard
Here's what you'll see for a successful build:
and for an unsuccessful build:
and an in-progress build:
FYI, I configured this `master` branch protection rule here: https://github.com/cardinalitypuzzles/smallboard/settings/branches

Set up Circle CI for continuous integration testing (#94)

---

answers/templates/queue.html
answers/urls.py
answers/views.py

Will optimize to query the modals from the server on-demand rather than pregenerating them in a follow-up PR.

Fix Answer Queue page (#89)

---

puzzles/templates/puzzles_table.html
puzzles/templates/title.html

This fixes https://github.com/cardinalitypuzzles/smallboard/issues/65.

All links should open new tabs

---

puzzles/forms.py
puzzles/views.py

Fixes https://github.com/cardinalitypuzzles/smallboard/issues/90

Fix bug in TagForm

---

hunts/views.py
puzzles/views.py

I hope you guys don't mind :).

Disable CSRF checks for add puzzle and add tag to allow scripting

---

puzzles/templates/puzzles_table.html

Move column search to top and auto-expand collapsed nodes upon search

---

hunts/templates/all_puzzles.html
hunts/views.py
puzzles/templates/puzzles_table.html
smallboard/templates/base.html

Minimal changes; figured they were worth trying to save off

Style the table with boostrap and add a bit of padding in some places

---

README.md
new-hunt-setup.md

You can read them here: https://github.com/cardinalitypuzzles/smallboard/blob/new-hunt-instructions/new-hunt-setup.md
For #95 / #12.

New hunt setup instructions

---

README.md
user-guide.md

See how it looks here: https://github.com/cardinalitypuzzles/smallboard/blob/user-guide/user-guide.md
Let me know if there's something I should add or clarify.

Small Board user guide

---

puzzles/views.py

Archive Slack channel when puzzle is deleted

---

answers/templates/queue.html
answers/views.py

I figured out how to change the row color without redrawing the table. Just a matter of removeClass/addClass on the tr element.

Don't redraw answers table for status update

---

hunts/templates/all_puzzles.html
puzzles/templates/modals/add_tag.html
puzzles/templates/modals/delete_puzzle.html
puzzles/templates/modals/edit_puzzle.html
puzzles/templates/modals/edit_status.html
puzzles/templates/modals/set_meta.html
puzzles/templates/modals/submit_answer.html
puzzles/views.py

It turned out some of my problems were due to having variables named as JavaScript reserved keywords (`name`, `status`).
Changes:
* made submitting answer asynchronous (won't reload the puzzles page)

Support submitting answer asynchronously

---

new-hunt-setup.md

Here's how the update instructions look: https://github.com/cardinalitypuzzles/smallboard/blob/slack-instructions/new-hunt-setup.md#new-hunt-setup
Refs:
* https://blog.rmotr.com/how-to-delete-multiple-slack-channels-at-once-7ba00f4890cd
* https://github.com/santiagobasulto/slack.py
* Mr. @asdfryan

Slack hunt setup instructions (how to delete channels)

---

hunts/templates/all_puzzles.html
puzzles/templates/modals/edit_puzzle.html
puzzles/templates/modals/edit_status.html
puzzles/templates/modals/set_meta.html

For #42, disables submit button for forms that reload the page.

disable form for puzzle adding and editing

---

google_api_lib/google_api_client.py
slack_lib/slack_client.py

Handle puzzle creation and deletion cases where Slack channel is already archived

---

puzzles/views.py

Should fix part of #157 (removing meta tag from a puzzle).

Commit database transaction before updating meta spreadsheet

---

hunts/templates/all_puzzles.html

Results in fewer table redraws by DataTables, reducing lag. Also added some short-circuit code when 'render' is called for filtering purposes.

Add 500 ms search delay to search box

---

puzzles/templates/modals/edit_status.html

Clear edit status modal after form submission

---

answers/views.py

The correct answer is now removed from the meta sheet's AUTOGENERATED sheet.

Fix meta sheet updating when puzzle answer changed from CORRECT to something else

---

hunts/templates/all_puzzles.html
hunts/templates/tools.html

fixed monospacing on main table

---

hunts/templates/tools.html

Replaced references to slack with discord, removed link to last year's hunt, added web

update tools page for 2021

---

google_api_lib/google_api_client.py

issue #183: shorten URL pasted into sheet

---

.env.test
dev-guide.md

Simplifies local development by avoiding the postgresql requirement since the sqlite3 database backend is built into Django.

Config sqlite env for local development

---

hunts/models.py
puzzles/models.py

ForeignKey/ManyToManyFields in other app Models are more generalized and
scalable this way.

Replace 'accounts.Puzzler' with get_user_model()

---

answers/tests.py
puzzles/templates/modals/submit_answer.html
puzzles/views.py

Fixes #168.
Deleted the validation on the JS-side since it's not needed.

Only strip whitespace from answers

---

smallboard/settings.py

See it at https://smallboard.app
Also fix the SECURE_SS_REDIRECT env variable check

Add smallboard.app to allowed hosts

---

hunts/src/hunt-view.js

refactor hunt-view to use idiomatic functional component style

---

Pipfile
Pipfile.lock
puzzles/urls.py
puzzles/views.py

Required for the hunt slug URL change in #201.

Fixes for heroku instance

---

puzzles/signals/handlers.py
puzzles/views.py

Simpler to just handle this in one place here. I tested adding/removing
metas with "Assign Metas" and with tags as well as deleting puzzles.

Move sheet update logic from views to signal hooks

---

api/urls.py
api/views.py
hunts/src/App.js
hunts/src/DeletePuzzleModal.js
hunts/src/HuntViewMain.js
hunts/src/NameCell.js
hunts/src/api.js
hunts/src/huntSlice.js
hunts/src/index.js
hunts/src/modalSlice.js
hunts/src/puzzle-table.js
hunts/src/puzzlesSlice.js
hunts/src/store.js
package.json
puzzles/models.py
puzzles/views.py
yarn.lock

Exactly the same interface as the current site. For #251, depends on #253 
Originally I wrote this UI without redux (mostly cuz I've never used it) but triggering things from inside the individual table cells (like opening a modal) was already getting complicated and there was no good way to make the UI reflect the changes instantly without waiting for a full refresh. So I bit the bullet and worked through some redux docs... I'm sure there's some unidiomatic or outright bad stuff in here.
There's a lotta boilerplate/scaffolding but hopefully now the other actions can just follow these patterns.

[React] Add redux, puzzle deletion UI/API

---

api/serializers.py
api/urls.py
api/views.py
hunts/src/AddPuzzleModal.js
hunts/src/EditPuzzleModal.js
hunts/src/GlobalFilter.js
hunts/src/HuntViewMain.js
hunts/src/api.js
hunts/src/puzzle-table.js
hunts/src/puzzlesSlice.js

Reasonably straightforward. I also included some small UI cleanups and polish (autofocus, front-end form validation)

[React] add Add Puzzle API/UI

---

api/serializers.py
api/views.py
hunts/src/HuntViewMain.js
hunts/src/alertSlice.js
hunts/src/api.js
hunts/src/store.js
package.json
webpack.common.js
webpack.dev.js
webpack.prod.js
yarn.lock

The two commits in this branch aren't really related to each other except that they're things I'm doing to make this more production-ready. Needed to stop running `watch` for the production webpack config, and also added some pieces for error handling, so that errors now generally produce sensible messages.

[React] Error handling and webpack improvements

---

api/serializers.py
api/urls.py
api/views.py
hunts/src/EditPuzzleTagsModal.js
hunts/src/HuntViewMain.js
hunts/src/TagCell.js
hunts/src/TagPill.js
hunts/src/alertSlice.js
hunts/src/api.js
hunts/src/constants.js
hunts/src/modalSlice.js
hunts/src/puzzlesSlice.js
hunts/src/utils.js

Add in the functionality to add/remove existing tags to a puzzle and to create new tags.
It looks a little shitty and the UX is a little shitty too but for the moment I'm just worried about the functionality.

[react] Puzzle tag API and UI

---

api/views.py

Fix transaction.on_commit bugs

---

hunts/src/puzzlesSlice.js

Fix UI error when deleting feeders

---

hunts/templates/all_puzzles.html

Still useful to have this working until we delete the old UI, for testing
purposes.

Fix add puzzle in non-react view

---

hunts/src/HuntViewMain.js

Rename Tags column to Tags/Metas in react UI per feedback from UMD test

---

api/views.py
chat/models.py
chat/tests.py
discord_lib/discord_chat_service.py
discord_lib/test.py
smallboard/settings.py

This does not include category sharding, which will be done in a future PR.

Archive discord channels upon solve

---

puzzles/models.py
puzzles/tests.py

assuming that we maintain that is_solved returns true iff at least one correct answer is present

Rewrite Puzzle solved_times using ORM

---

api/views.py

Fix answer creation/deletion

---

answers/tests.py
api/test_helpers.py
api/urls.py
api/views.py
hunts/src/api.js
puzzles/tests.py

The nesting was too deep and unnecessary for puzzle tags and puzzle
answers.

Remove /hunts/ from some API endpoints

---

docker-compose.yaml

Share .env with celery workers in Docker

---

api/views.py
google_api_lib/task.py

Fixes #135
Didn't put the answer in there since multiple answers makes it a little
more complicated; figure this is the important info anyway.

Rename sheet when puzzle is solved

---

hunts/src/EditPuzzleTagsModal.js
hunts/src/EditableTagList.js
hunts/src/TagPill.js

Instead of a display of tags at the top that you can click to add, and a
list of all your tags at the bottom that you can use to remove, try just
toggling each tag on/off.
Played around a little while with the visuals and this is the best I had
so far but it's still a little ugly imo.
Thinking of using a UI like this to implement #68

Try revamping the edit tags modal

---

hunts/src/HuntViewMain.js

in service of https://github.com/cardinalitypuzzles/smallboard/issues/348

add 30 pixel margins on the left and right of smallboard hunt UI

---

Pipfile
Pipfile.lock
Procfile
chat/management/commands/rundiscordbot.py
smallboard/settings.py

Still very rough around the edges, but seems to work. Currently supports
sending a command starting with `!puzzles`. By default, the command
lists unsolved puzzles, but you can supply a subcommand like `!puzzles
stuck` to view all puzzles with STUCK status. Current commands:
- `!puzzles`
- `!puzzles unsolved`
- `!puzzles solved`
- `!puzzles stuck`
Still need to implement:
For #214

Initial Discord bot implementation

---

google_api_lib/task.py

Let's see what happens, somewhat related to #353

remove update_meta_sheet_feeders rate limit

---

hunts/src/EditAnswerModal.js
hunts/src/EditPuzzleModal.js
hunts/src/SubmitAnswerModal.js

Autofocus some modal fields when the modals open

---

hunts/src/HuntViewMain.js
hunts/src/solveStateFilter.js

rename 'priority' to 'unsolved' and remove 'unsolved' option

---

answers/templates/queue.html
smallboard/templates/base.html

This was giving some (harmless) console errors on the main page and breaking the answer queue too.
Moved some things to the answer queue page to keep that one working.

Clean up some 3rd party libraries

---

hunts/templates/stats.html

so that the chart works
(also discarded stray comment)

Rebundle moment.js in stats.html

---

api/views.py
chat/models.py
chat/service.py
chat/tasks.py
discord_lib/discord_chat_service.py

Figured I might as well do this now. The discord API is fairly
responsive but I'd noticed it was still introducing some lag to a lot of
interactions.

Chat operations as Celery tasks

---

hunts/src/HuntViewHeader.js

Add link back to hunt index in header

---

chat/models.py

Probably useful information to try to send to solvers (eg a meta gets
solved and this puzzle is no longer useful)
Fixes #388

Send message to puzzle channel if a puzzle is marked high/low pri

---

hunts/templates/all_puzzles_react.html
smallboard/settings.py

Let's see whether this works....?

switch to REDIS_TLS_URL for channels

---

api/views.py

Rename sheets when puzzles are renamed

---

chat/fake_service.py
chat/models.py
chat/service.py
discord_lib/discord_chat_service.py
discord_lib/test.py
smallboard/settings.py

Fixes #442
Tested this in a test Discord server so I feel ok about it

Add separate categories for text and voice channels

---

api/views.py
chat/tasks.py

Added puzzle rename announce

---

google_api_lib/sync_tasks.py
google_api_lib/tasks.py
google_api_lib/tests.py
smallboard/settings.py

ignore celery results

---

new-hunt-setup.md

For a preview of how the updated docs look, see https://github.com/cardinalitypuzzles/smallboard/blob/erwa/more-docs/new-hunt-setup.md

Add Discord-related setup instructions and environment variables to new-hunt-setup.md

---

api/tests.py
api/views.py

Do not change color of a meta tag

---

cardboard/static/style.css

Fixes #479
This is overriding a bad bootstrap style

Vertically center table contents

---

.gitignore

Add neovim config to gitignore

---

api/views.py
hunts/src/StatusCell.js

Allow moving status to SOLVED if there's at least one correct answer

---

api/test_helpers.py
api/tests.py

I didn't think about the API for this very much (so there might be a better one) but I guess it's loosely inspired by abseil's ASSERT_OK at Google

Add a test helper for checking API status codes

---

api/views.py

Previously this was only firing on answer deletion, not on status changes.

Send unsolve messages/update sheet titles when status is marked unsolved

---

api/test_helpers.py
api/tests.py
api/views.py
puzzles/models.py

rename sheet titles for backsolves and add answers

---

google_api_lib/tasks.py

iss #480: change autogenerated column order

---

cardboard/static/style.css
cardboard/templates/base.html

adds toggle for light and dark mode

---

hunts/src/HuntViewMain.js

I missed a spot keeping things connected in my last PR. This PR fixes it.

Fix bug I introduced

---

cardboard/templates/base.html

add link to github in footer

---

cardboard/static/style.css

I don't know much about color but this feels better to me?
Before
After
Light mode (unchanged)
Dark mode (improved)

improve dark mode colors

---

hunts/src/ChatCell.js
hunts/src/HuntViewMain.js
hunts/src/chatSelector.js
hunts/src/chatSlice.js
hunts/src/constants.js
hunts/src/store.js

So that those with app installed can click to open discord and change to the proper text channel.

add option to switch discord links from https:// to discord://

---

cardboard/static/style.css

It was really harsh on the eyes
Before
After

darken dark mode green

---

cardboard/templates/tools.html

Added a few more tools and updated last year's web to this years

update tools page

---

answers/admin.py
chat/admin.py
puzzles/admin.py

Just makes the tables a bit nicer and easier to filter, mostly relevant for ChatRole.

Usability improvements to admin interface

---

hunts/src/DeletePuzzleModal.js

Addresses https://github.com/cardinalitypuzzles/cardboard/issues/545
Before
After

add puzzle title to delete modal body

---

cardboard/settings.py
poetry.lock
pyproject.toml

Not using it any more after #474

Remove django-celery-results

---

cardboard/templates/tools.html

remove maxims and add section for additional sheet templates

---

hunts/src/TagPill.js
hunts/src/constants.js

* Sentence case for better readability
* Add small amount of spacing between them
* Sort default tags alphabetically within each group

Puzzle tags: UI tweaks

---

api/tests.py
api/views.py
chat/models.py
hunts/src/constants.js
hunts/src/puzzlesSlice.js
puzzles/models.py
puzzles/puzzle_tag.py
puzzles/tests.py

Similar to backsolved, when I changed the casing of the tags I broke these
Unlike backsolved I didn't make this any more robust because I don't have time right now.

Fix high/low priority tags

---

hunts/src/EditPuzzleTagsModal.js
hunts/src/TagCell.js

Before there was no indication of which puzzle you were actually editing

Show puzzle name in the edit tags modal

---

chat/tasks.py

fix silly bug

---

yarn.lock

I think (?) this updates all the js packages except react-table, which had a patch that seemed somewhat cumbersome to update.

update js packages

---

dev-guide.md

Had a fresh install of windows / WSL / Ubuntu and found that these were needed as well.

add two libraries to dev guide that were needed for WSL

---

.env.test
cardboard/context_processors.py
cardboard/settings.py
cardboard/templates/home.html
cardboard/templates/privacy.html
new-hunt-setup.md

change email address to use env var

---

chat/models.py
discord_lib/discord_chat_service.py

Discord part 2: Re-enable messaging

---

hunts/src/GlobalFilter.js

Improve search placeholder

---

chat/tasks.py

bold puzzle title + mono answer

---

api/views.py
cardboard/templates/base.html
chat/models.py
chat/tasks.py
hunts/src/AddPuzzleModal.js
hunts/src/EditPuzzleModal.js
hunts/src/NameCell.js
hunts/src/puzzlesSlice.js

https://www.loom.com/share/9b7122d9eb3342be99f234c8e261f95d

Optional discord

---

cardboard/templates/home.html
dev-guide.md
new-hunt-setup.md

Hi there, thanks for building Cardboard! We've been using it for the past six months or so.
Would you be interested in a small patch to update some instances of "whitelist"? Thanks!

Updates language to use "approved list".

---

Procfile
api/serializers.py
cardboard/celery.py
cardboard/settings.py
docker-compose.yaml
google_api_lib/tasks.py
google_api_lib/utils.py
puzzles/admin.py
scripts/add_service_account_contacts.py
scripts/cleanup_service_account_contacts.py

A few changes to make active users backwards compatible or more robust.

few improvements to active users

---

hunts/src/AddPuzzleModal.js

Set default for puzzle discord channel creation to true 

---

hunts/src/HuntViewMain.js

Make modals scrollable.

---

cardboard/static/style.css
hunts/src/AnswerCell.js

Address #704 by setting a max-width of 400px for answers and wrapping them if they exceed the max width.
Before:
After:

Max answer width

---

new-hunt-setup.md

- mention that new Heroku apps have hex IDs in their subdomains
- link to Heroku docs for setting up a new app
- link to the Heroku Redis add-on (which is actually now confusingly called "Heroku Data for Redis")
- you need to log in before giving yourself superuser

update hunt setup docs more

---

chat/models.py

Fix ChatRole admin display

---

hunts/src/NameCell.js

de-dup tag

---

api/serializers.py
api/tests.py
api/views.py
hunts/src/NameCell.js
hunts/src/UsersCell.js
hunts/src/puzzle-table.js

Green = <5min
Yellow = 5-30min
Red = >30min

add last active time

---

Dockerfile
docker-compose.yaml
hunts/management/commands/celery_worker.py

Make celery autoreload on changes in development

---

cardboard/static/style.css
hunts/src/GlobalFilter.js

adds an X to the search bar and makes the ESC key clear it

---

hunts/src/LinkCell.js

Fixes #708
[Screencast from 2024-01-11 17-01-37.webm](https://github.com/cardinalitypuzzles/cardboard/assets/6751517/d570b52e-f77b-48b2-a2ca-19388734ed81)

Add button to create Discord channels in Hunt table

---

google_api_lib/tasks.py
hunts/models.py
hunts/templates/stats.html
new-hunt-setup.md

Haven't tested this yet, but this may fix https://github.com/cardinalitypuzzles/cardboard/issues/810

Fix dupe permission error

---

chrome_extension/cardboard/popup.html
chrome_extension/cardboard/popup.js

When a puzzle has already been created, you can now 
- Change its status
- Set an answer
- Assign it to a new meta
- Mark as backsolved

Further improve Chrome Extension functionality

---

hunts/src/NameCell.tsx
hunts/src/TagPill.tsx

I probably screwed it up in the last commit sry

fix badge text color

---

hunts/src/EditPuzzleModal.tsx
hunts/src/NameCell.tsx

menu cleanup #2: tuck 'delete puzzle' under edit puzzle menu

---

hunts/src/AddPuzzleModal.tsx
hunts/src/EditAnswerModal.tsx
hunts/src/EditNotesModal.tsx
hunts/src/EditPuzzleModal.tsx
hunts/src/SubmitAnswerModal.tsx

Prevents password managers from mistakenly autofilling names, etc.

Turn off autocomplete in form modals

---

hunts/src/AddPuzzleModal.tsx

Ensure that Add Puzzle modal uses the current set of tags

---

.pre-commit-config.yaml
hunts/src/AnswerCell.tsx
hunts/src/DarkModeToggle.tsx
hunts/src/DeleteAnswerModal.tsx
hunts/src/EditPuzzleModal.tsx
hunts/src/HuntViewHeader.tsx
hunts/src/LinkCell.tsx
hunts/src/NameCell.tsx
hunts/src/NotesCell.tsx
hunts/src/SiteHeader.tsx
hunts/src/StatusCell.tsx
hunts/src/TagCell.tsx

Make sure pre-commit runs prettier on jsx/ts/tsx files
