cardinalitypuzzles/cardboard

- answers/templates/queue.html
- puzzles/templates/puzzles_table.html
Add same search functionality in Answer queue view, with added text-input search enabled for the Notes field. Previously this just didn't work at all.
> Support search / column filtering in Answer Queue

- puzzles/templates/puzzles_table.html
Tested locally -- see screenshots below.
Original page:
Basic column filter works:
It filters on the right column:
Combinations of filters also work:
> Enable column-search for a few columns in the puzzles table.

- puzzles/templates/puzzles_table.html
- smallboard/settings.py
Per discussion in #38.
Regarding the print() to logger.info() change -- the print() statement would always run on start-up and print out a list of whitelisted emails, and I started to find it kind of annoying. The logger.info() message isn't printed by default, I guess because the default log level is WARN. I like this better; for dev, if needed, a dev can change the log level to INFO (or lower) if desired.
Already deployed the changes to production :).
> Changed "Puzzle" heading back to "Name"; also switched print() statement to logger.info()

- puzzles/forms.py
- puzzles/models.py
- puzzles/templatetags/puzzle_extras.py
Restrict UI to only allow changing to SOLVING, STUCK, or EXTRACTION. PENDING/SOLVED should be handled by the answer queue.
> Restrict puzzle status update

- answers/models.py
- answers/views.py
puzzles/models.py imported answers/models.py which in turn imported slack_client.py. 
I thought about this briefly, and think the right thing to do is to disallow any models from calling slack_client.py (because slack_client itself relies on the Puzzle model). Not sure if this is the best thing to do.
> Remove circular import

- puzzles/models.py
If puzzle A is a meta of B, B is not necessarily meta of A (in fact it shouldn't be).
> metas field should be asymmetrical

- puzzles/templatetags/puzzle_extras.py
- puzzles/views.py
This was the error I got with the latest code: http://dpaste.com/0Y2QCQC
```
Traceback:
File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
34.             response = get_response(request)
File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
115.                 response = self.process_exception_by_middleware(e, request)
File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```
> Fix 500 error due to meta_select KeyError

- puzzles/models.py
- puzzles/templates/puzzles_table.html
- puzzles/templatetags/puzzle_extras.py
- puzzles/urls.py
- puzzles/views.py
You can use it by clicking on the pencil icons.
It opens up a popup that's essentially the same as the New Puzzle form, but fields defaulted to the current model's fields.
Validation on dup puzzle names/urls, and invalid meta state.
> Add edit functionality for puzzle name, url, and meta status

- smallboard/settings.py
In preparation for Sunday's playtest, we may want to just create a new hunt and leave the test hunt around.
I've already added ACTIVE_HUNT_ID as a ConfigVar on our Heroku deployment.
> Make ACTIVE_HUNT_ID a configurable environment variable

- puzzles/forms.py
- puzzles/puzzle_tag.py
For #69, reserving
- red for High Priority
- green for Backsolved
- yellow for Low Priority 
- black for meta tags
> reserve tag colors

- puzzles/tag_utils.py
- puzzles/templates/modals/add_tag.html
- puzzles/templates/modals/tags_form.html
- puzzles/templates/puzzles_table.html
- puzzles/templates/show_tags.html
- puzzles/templatetags/puzzle_extras.py
- puzzles/urls.py
- puzzles/utils.py
- puzzles/views.py
- smallboard/settings.py
I followed in the footsteps of giants and copied the approach from #86 to remove pre-generation of all the tags modals and to fetch them on demand from the server.
With this change deployed, Small Board (with its ~70 puzzles) takes about 3 seconds to load (reduced from 5-6 seconds before) and data transferred is 456 KB (down from 1.1 MB):
> Use JavaScript to fetch tags modal (#84)

- answers/templates/queue.html
- answers/urls.py
- answers/views.py
- puzzles/templates/modals/delete_puzzle.html
- puzzles/templates/modals/edit_puzzle.html
- puzzles/templates/puzzles_table.html
- puzzles/templates/title.html
- puzzles/templatetags/puzzle_extras.py
Instead of pregenerating 1 edit puzzle modal and 1 delete puzzle modal per puzzle, this PR changes the code to just reuse a single edit puzzle modal and a single delete puzzle modal across all puzzles, and uses JavaScript to update the modals when the edit or delete icons are clicked.
Data transferred and load time is further reduced with this change:
Ignore the CircleCI results, since there's no config file until #97 is merged.
> Render edit and delete puzzle modals on demand instead of pregenerating 2 modals per puzzle (#84)

- README.md
- puzzles/models.py
I wasn't able to get Django fixtures to work because our puzzles/signals/handlers cause some integrity constraints to be violated, and it didn't seem easy to fix.
As an alternative, I just used Postgres's tools for taking a database dump and restoring from it. This PR adds instructions for how to do this to copy the production data into your local database.
@daiweili
> Add instructions for loading production data into local database

- puzzles/templates/puzzles_table.html
This means we rerender treegrid (should be cheap now that we have paging) on:
* new pages
* searches
> Enable paging by default and rerender treegrid on draw.dt events

- answers/forms.py
- answers/templates/queue.html
- answers/views.py
- hunts/views.py
- puzzles/forms.py
- puzzles/templates/puzzles_table.html
- puzzles/templatetags/puzzle_extras.py
- puzzles/views.py
- smallboard/static/jquery.dataTables.js
- smallboard/templates/base.html
Server side: prefetch_related on hunts.puzzles.all() to trim number of SQL queries from O(# puzzles) to O(1)
Client side: use modified version of dataTables to extract text straight out of the DOM API rather than extracting text out of the DOM, re-parsing using jQuery, and then extracting the desired text out of jQuery (each re-parse takes ~5ms, extracting out of the DOM API is > 100x faster)
> Performance improvements

- .circleci/config.yml
- answers/tests.py
Answer Queue page was broken inadvertently in #118 (still needs to be fixed). But to prevent this from happening in the future, this PR adds a test that verifies `/answers/queue/X` returns 200. Ref: https://github.com/cardinalitypuzzles/smallboard/pull/118#pullrequestreview-337164371
> Add test that verifies Answer Queue page loads successfully

- answers/views.py
On Heroku:
before the change, fetching answers took ~3 sec:
after the change, it takes about 1.25 sec:
> Use prefetch_related('puzzle') on answers query

- answers/templates/queue.html
- answers/views.py
Answer Queue page now refreshes asynchronously every 3 seconds, without a full page reload. Updating answer status also happens asynchronously and doesn't trigger full page reload.
Table is only redrawn if new answers have been submitted.
I plan to make updating the Notes field asynchronous (rather than triggering full page reload) in a subsequent PR.
> Refresh Answer Queue table asynchronously (without full page reload), make update status asynchronous

- answers/views.py
- puzzles/views.py
- slack_lib/slack_client.py
Changes:
* send answer status update messages to separate #answer-queue channel for easier monitoring by phone person
* add Slack messages for NEW and SUBMITTED status updates
* post CORRECT status update message to puzzle channel as well
* move puzzle creation and CORRECT answer messages from #announcements to #puzzle-announcements
Screenshots:
In puzzle channel:
In #answer-queue channel:
> Send answer queue messages to separate #answer-queue channel

- hunts/views.py
- slack_lib/slack_client.py
In #puzzle-announcements:
In puzzle channel:
Also linkified the Slack channel name posted to the #puzzle-announcements channel.
For #134.
> Share puzzle link and sheet link in Slack messages

- answers/views.py
- slack_lib/slack_client.py
and unarchive it if answer status changed again to something else
and edge case where one guess is marked CORRECT and then a different guess for the same puzzle is marked INCORRECT (we unarchive the channel temporarily to send the INCORRECT status update and then re-archive the channel):
For #133
> Archive Slack channel on CORRECT answer

- puzzles/puzzle_tag.py
- puzzles/tag_utils.py
- puzzles/views.py
Intermittently, in the "Add Tag" form, there will not be any options in the color dropdown menu:
This seems to be due to some class initialization race condition. By generating the visible color choices and color ordering in class methods, the issue goes away.
> Fix missing colors in dropdown in "Add Tag" form

- puzzles/tag_utils.py
For puzzles that require going somewhere on-campus.
> Add INTERACTIVE as a default tag

- answers/forms.py
- answers/templates/queue.html
- answers/views.py
I think I'm finally starting to understand how JavaScript handlers work...
Changes:
* support updating Notes without page reload. The table row flashes (disappears and fades in) as visual feedback upon submitting the Notes field
* added support for clearing deleted Notes (by making it not a required field)
> Support updating Notes for answer asynchronously

- hunts/templates/all_puzzles.html
- puzzles/templates/modals/submit_answer.html
- puzzles/templates/modals/tags_form.html
- puzzles/views.py
- smallboard/templates/base.html
Changes:
* made adding and removing tags asynchronous (no reload)
* added alert message on AJAX success / error
Add tag message:
Remove tag message:
Submit answer message:
Trying to delete meta tag from meta:
This PR includes the commits from #144.
> Support adding and deleting tags without reload

- puzzles/templates/modals/set_meta.html
- puzzles/views.py
Suppose puzzle44 looked like this:
and then you updated the assigned metas as follows: (remove Anger and Sadness, add Fear and Disgust)
then (with these changes) on Submit, no page reload will happen, and you'd see:
and the treegrid will get redrawn once reload() finishes.
> Support "Assign metas" without page reload

- puzzles/templates/modals/edit_status.html
- puzzles/views.py
Here's what the update puzzle status message looks like:
> Support updating puzzle status without page reload

- puzzles/templates/modals/edit_puzzle.html
- puzzles/templates/modals/submit_answer.html
- puzzles/views.py
Example success message when puzzle 'Anger' was renamed to 'Angering':
>  Support editing puzzle (name, URL, is_meta) without page reload

- hunts/templates/all_puzzles.html
- puzzles/templates/modals/delete_puzzle.html
- puzzles/views.py
Example message when deleting a puzzle 'test':
> Support deleting puzzle without page reload

- hunts/templates/all_puzzles.html
- hunts/views.py
Filling out the form: note X button, Cancel, and Add are all present and clickable
On form submit: X button is removed, Cancel is grayed out, Add changes to "<spinning wheel> Creating puzzle"
On success:
On error:
> Support adding new puzzle without page reload

- .github/workflows/pre-commit.yaml
Automatically checks pre-commit linters on pull requests and commits to
the master branch. This actually enforces the pre-commit changes added
in https://github.com/cardinalitypuzzles/smallboard/pull/198.
See https://github.com/pre-commit/action for docs on the action used here.
> Add pre-commit github actions workflow

- smallboard/settings.py
Force people to use HTTPS in prod (right now both work).
I already updated the config var in Heroku but we also need to update the python side.
> Add HTTPS redirect support for production

- hunts/templates/all_puzzles.html
Fixes #159.
Fixes #119.
The initTreegrid function seems to blow away the expander arrows
somehow. Telling it to rerender those whenever we recreate the treegrid
seems to do the trick.
Also moved some code to set callbacks to a better place.
> Redraw expander arrows when changing the table

- .github/workflows/pre-commit.yaml
- .github/workflows/pre-submit.yaml
~~This relaxes the requirements for merging PRs to other PRs or non-master branches.
@pcvera since you're authoring PRs targeting @rgossiaux's PR for the react rewrite, I figure we shouldn't block the changes on presubmit checks until it's time to merge the whole thing into master (a.k.a. the main branch).~~
@erwa pointed out that we can still leave these presubmits to run on any PR without blocking merging as long as we don't merge into the master (protected) branch. In that case, this PR just renames the workflow as a cleanup.
> Rename pre-commit workflow to pre-submit

- .pre-commit-config.yaml
- always run check-merge-conflict
- remove requirements.txt fixer (since we don't use that file anymore)
> Clean up pre-commit checks

- api/serializers.py
- api/urls.py
- api/views.py
- hunts/src/EditPuzzleModal.js
- hunts/src/HuntViewMain.js
- hunts/src/NameCell.js
- hunts/src/StatusCell.js
- hunts/src/api.js
- hunts/src/puzzlesSlice.js
- puzzles/models.py
- puzzles/views.py
They're implemented separately in the commit history to view them separately. Once the API to edit a puzzle is in place, changing puzzle status (only between solving/stuck/extraction) is nearly free fortunately.
For #251; depends on #256 and transitively on #253.
> [React] Add API/UI for editing puzzles and changing puzzle status

- dev-guide.md
Doesn't get into too much detail, but hopefully helps some folks to run React views
> Add basic React dev docs to dev-guide

- hunts/views.py
- smallboard/settings.py
What it says. I haven't added tests or checked very hard that this doesn't break other stuff and honestly what I did seemed a bit too simple.
Just to be clear, this PR is meant to, if no discord API token is in config, just not create discord channels (but otherwise do the same things).
> Handle the no-discord-API-token case

- api/serializers.py
- hunts/src/EditPuzzleTagsModal.js
- hunts/src/HuntViewMain.js
- hunts/src/TagPill.js
Since adding/removing tags also handles meta assignment, this column is
a little redundant. Removing it makes the table less busy and unifies
the UI a bit by having everything go through tags.
> Remove Assign Meta column

- hunts/src/constants.js
- hunts/src/puzzlesSlice.js
Fixes #286
This is a little hacky, I think. Ideally the API wouldn't let you create
tags with reserved colors. In that case the default tags need to exist
in python (passed down as part of the hunt info, probably)
and then the API validation needs to be updated.
Other things are higher pri than making this work elegantly though so
this is good enough for now.
> React: Include default tags in add tag modal

- discord_lib/discord_chat_service.py
- discord_lib/test.py
We store channel_id as string, but discord API returns/expects int.
> Fix bug related to discord channel deletion

- .gitattributes
Git on windows automatically converts line endings to CRLF on checkout,
which makes these patch files not readable inside Docker. This should
(hopefully) exclude the patch files from this and fix the problem on
Windows though since I don't have a Windows machine I haven't actually
tested it.
> Fix windows line ending issue with Docker

- Dockerfile
- docker-compose.yaml
Fixes #313.
The node_modules/ directory generated in the image was getting bypassed
when we mounted the source code directory. Specifying it as another
volume somehow seems to fix this.
Also deleting the code copying line from the Dockerfile since it's
misleading and unnecessary with the volume.
> Fix node_modules Docker issues

- answers/tests.py
- api/serializers.py
- api/test_helpers.py
- api/tests.py
- api/urls.py
- api/views.py
- hunts/src/api.js
- puzzles/tests.py
- smallboard/settings.py
These could be improved / made more complete but I think it's a start, and it's more testing than the old endpoints had anyway.
> Add initial batch of unit tests for the React API

- .codecov.yml
- .env.test
- dev-guide.md
Added a reminder in dev-guide.md to set up `.env`, which is required by our Docker and manual setups.
```
$ docker-compose up
ERROR: Couldn't find env file: /home/erwaman/github/cardinalitypuzzles/smallboard/.env
```
> Add section in dev-guide to setup .env

- hunts/src/puzzle-table.js
Fixes #290
Opening/closing a modal re-renders the parent component; since the PuzzleTable
is a pure component we can wrap in React.memo and only rerender when
props (ie data) change.
> Fix modals causing table rerenders

- google_api_lib/task.py
- google_api_lib/utils.py
The scripts were broken (#169) because copying the sheets template sets the owner to a service account, which is unable to run scripts. This change transfers ownership back to original owner of template.
> transfer ownership of sheets after creation

- api/tests.py
Ignore whatever chat settings in your local .env file.
> Disable chat features in api unit tests

- google_api_lib/task.py
- google_api_lib/tests.py
- google_api_lib/utils.py
- google_api_lib/whitelist.py
A few changes for #327 that hopefully makes sheets creation more robust:
- Separates sheets creation and transferring of sheets ownership from service account to user account. The latter was failing due to a sharingRateLimitExceeded error, which according to [this stackoverflow](https://stackoverflow.com/questions/46844246/drive-api-sharingratelimitexceeded-error) is because there is a 50 permission creation per day, although I couldn't find this quota in the official google API docs. 
- Switch from permission creation to permission update, which for some reason is not quota-ed. I wrote a script to update the permissions for the hundreds of existing sheets and I didn't see that error again, so hopefully that means this will not break mid-hunt. Even if it does break, creation and ownership …
> Fix sheets 

- discord_lib/discord_chat_service.py
- hunts/src/HuntViewMain.js
Stop generating invite links and use /guild_id/category_id instead. Also stop showing voice links which are useless.
> Remove voice chat link (currently useless), and stop calling Discord API to generate invite links

- answers/views.py
- api/views.py
- google_api_lib/task.py
- puzzles/signals/handlers.py
update_meta_sheet_feeders no longer checks if the google API is enabled,
so callers need to do it.
We also don't check if there's a sheeet url, so do that too.
> Some fixes/safety for meta sheet updates

- smallboard/settings.py
For logging exception data when DEBUG=False (ie production). By default
they're swallowed without configuration.
> Add logging config to settings.py

- smallboard/settings.py
This setting seems to be distinct from CELERY_REDIS_MAX_CONNECTIONS
> Lower CELERY_BROKER_POOL_LIMIT to two connections

- Dockerfile
So that everything in Docker uses the timezone of smallboard instead of UTC.
> Add tzdata to Dockerfile

- smallboard/settings.py
Looks like this is one connection pool per worker process (and multiple
worker processes run at once) so keeping this small. Can also try None
for no connection pool (new connection every time) if we have to.
> Lower worker connection pool 2 => 1

- Procfile
Some suggestions online to disable these for keeping redis connection
counts down as they all add extra connections. Gossip is only used for
clock sync, mingle is only for some inter-worker sycnhronization
(especially for letting new workers know about unprocessed revoked
tasks--not something we need to worry about as our worker pool will be
constant and we won't be revoking tasks), heartbeat is useless as we
only have one redis node.
> Disable celery heartbeat, gossip, mingle

- api/serializers.py
- api/tests.py
- hunts/src/HuntViewMain.js
- hunts/src/constants.js
Makes /puzzles responses almost 25% shorter. Hard to say precisely how
it affects the response time (too variable) but it appears to be a nice
improvement as well which is what I would expect. The only downside is
that opening a sheet is now a little slower since we have to do the
redirect.
> Use sheet redirect endpoint on the frontend

- hunts/src/HuntViewMain.js
- hunts/src/puzzle-table.js
Add `.Answer` to the search field, understanding that `.answer` was removed during multi-answer support. (please confirm @rgossiaux @asdfryan)
> fix answer filter regression

- hunts/src/puzzlesSlice.js
Fixes #328.
Thought about trying to retry the fetch but since we fetch every several
seconds anyway it didn't seem necessary (plus it could bunch up several
at once which could be undesirable).
> Prevent stale fetches from overwriting changes

- hunts/src/solveStateFilter.js
Fixes #341.
react-table does some buggy stuff modifying subRows, so making a copy in
your filter function is the easiest way to deal with it--had to do
something similar with useGlobalFilters for the search bar.
> Fix bad expand/filter interaction

- hunts/src/StatusCell.js
`SOLVED` is only listed as an option for solved puzzles. (i.e. it is only possible to "SOLVE" a puzzle by adding an answer)
> Make status editable even after marked as SOLVED

- chat/management/commands/rundiscordbot.py
* Use shortened sheet redirect URLs
* Add links to chat channels
* Use one puzzle per field instead of grouping multiple puzzles inside the same field
* Add paging across multiple messages
You can see the latest on #bot-spam. I've also turned off manual deploys for cardi P and it's deployed to the latest on this branch manually for now so you can interact on discord yourself.
> Discord bot: paging, chat links, tweaks

- hunts/src/constants.js
To make it match the "cryptics" role on Discord
> Add CRYPTICS to list of default tags

- hunts/chart_utils.py
- hunts/tests.py
time datapoint is set to chart_start_time if made/solved before chart_start_time
> Chart accounts for puzzles made/solved before start time

- smallboard/settings.py
I think we still want all http to redirect to https
> put back SECURE_SSL_REDIRECT

- new-hunt-setup.md
Markdown is tricky. Apparently for straight-up URLs, you don't need to surround with brackets or add parentheses after the brackets.
> Fixed broken https://console.developers.google.com/ link

- dev-guide.md
- new-hunt-setup.md
clarify some other steps.
* Updated Discord OAuth2 URL Generator page instructions
* Added alternative way of setting buildpacks (from Heroku app settings
page)
* Clarify that GOOGLE_API_PRIVATE_KEY should be in the downloaded JSON
file when you added a key
* mention you need to enable "Google Drive API" and "Google Sheets API"
in your Google Cloud project
* recommend setting `DJANGO_SECRET_KEY` and `DEBUG=False` in new-hunt-setup.md
* Add link to Heroku CLI doc page
------
You can see how the updated docs look at:
* https://github.com/cardinalitypuzzles/smallboard/blob/erwa/docs-enable-drive-and-sheets/dev-guide.md
* https://github.com/cardinalitypuzzles/smallboard/blob/erwa/docs-enable-drive-and-sheets/new-hunt-setup.md
> Add enabling Google Drive and Google Sheets API to new-hunt-setup.md and

- new-hunt-setup.md
Need to go to APIs & Services > Credentials > click your OAuth2 client >
under "Authorized redirect URIs", click ADD URI and add
https://<YOUR_APP>.herokuapp.com/complete/google-oauth2/
See updated docs here: https://github.com/cardinalitypuzzles/smallboard/blob/erwa/add-whitelist-oauth2/new-hunt-setup.md
> Added instructions for whitelisting the Google OAuth2 login URI

- api/tests.py
- api/views.py
> If a tag has the same name as a non-meta puzzle, let it be removed

- api/views.py
For #446, but I doubt this fixes it.
> Add transaction.atomic() block for editing puzzle answers

- cardboard/settings.py
- google_api_lib/sync_tasks.py
- new-hunt-setup.md
Before, the list of whitelisted emails was only calculated once at start-up time, and every time you added a user, you would need to restart Cardboard before that user could log in.
Now we just query the list of emails added to the Google Drive as part of the authentication flow. So as soon as you add a user to a Google Drive, they should be able to login to Cardboard.
The Google Drive API to get the folder permissions is pretty fast, so it doesn't noticeably slow down the login. Also, according to https://support.google.com/a/answer/10445916?hl=en, the default Drive API quota is 10,000 calls every 100 seconds, which is plenty for us.
My implementation of `auth_allowed` is based off the default `auth_allowed` implementation here:
* …
> Query whitelisted emails at authentication time (fixes #500)

- README.md
- hunts/src/EditableTagList.js
- hunts/src/constants.js
- hunts/src/puzzlesSlice.js
* Adds new tags
* Sorts the tags according to how the defaults list was defined in constants.js. 
* Currently, that means high pri, low pri, backsolved, and slog tags are first row and then the other tags alternate blue/white per row, roughly aligned to their subject area. The code to split the tags into rows is admittedly a little jank.
We'll want to eventually move this stuff in the DB but I sorta want to continue kicking this can down the road unless someone feels really strongly about it.
> iss #452: Update default tag list

- cardboard/celery.py
Pipenv would automatically load .env files, so it didn't matter if the celery workers didn't. Celery stopped working in local development after switching to poetry, which ignores .env files. It didn't break prod, since the environment variables are set in the Heroku apps instead of through .envs.
> load .env file in celery workers

- cardboard/static/style.css
- hunts/src/AnswerCell.js
- hunts/src/ClickableIcon.js
- hunts/src/NameCell.js
- hunts/src/TagCell.js
The UI needs more work than this (especially the answer cell) but I think it's a step in the right direction. Looks a lot cleaner to me without twenty pills popping out the screen at once.
Before: 
After:
> Remove the border/background around the icons

- api/views.py
- chat/models.py
- chat/service.py
- chat/tasks.py
- discord_lib/discord_chat_service.py
Delete voice channels and text channels that contain no non-bot messages 30 minutes after a puzzle is marked as SOLVED.
For puzzles with multiple answers, the cleanup is avoided by marking the puzzle as SOLVING after putting in the first answer.
> clean up channels 30 minutes after puzzle solve

- discord_lib/discord_chat_service.py
Fixes #546
Important so that the roles from last year's hunt don't interfere with the notifications
> Check that hunt matches for discord @ mentions

- hunts/views.py
Otherwise everyone from last year will get sent to the 2021 hunt page after logging in. This way they get sent to the index page.
> Don't redirect to most recent hunt if it's not active

- hunts/src/LinkCell.js
- hunts/src/puzzle-table.js
* Force the links to always appear on one line (previously they break onto two or three lines as the screen shrinks)
* Set some basic proportions for the columns widths (tested using last year's hunts and a new hunt)
Last year's MH on my full width laptop screen: 
Empty hunt on full width laptop screen:
As the screen width goes down this matters less and less because the table layout is constrained by wide elements (long answers/tags/words)
> Table column width fixes

- google_api_lib/tasks.py
- google_api_lib/tests.py
- hunts/models.py
Fixes #541
This lets us keep the template in a different location from the puzzle files, which is useful
if we're potentially going to make a bunch of copies of the template in advance and need to
distinguish those from puzzle sheets.
> Use the Drive folder ID for storing puzzle files instead of the same directory as the template

- .github/workflows/pre-submit.yaml
Better to use the same environment as production IMO. Noticed this because of #570  where tests fail on GH because it's using sqlite.
> Attempt to switch GitHub actions to using Postgres

- app.json
I think (?)
Before they were pointing at our prod database (yikes) which caused problems with migrations. This should give them their own config vars.
> Add separate review app add-on plans

- api/tests.py
- api/views.py
- puzzles/models.py
- puzzles/tests.py
I broke this when I changed the casing of the default tags. Making this case-insensitive.
> Fix the backsolved tag/sheet renaming interaction

- hunts/migrations/0008_huntsettings_backfill.py
#573 broke this migration since it removed DISCORD_GUILD_ID from settings.
We can wait until after the hunt to merge this in.
> fix backfill migrations

- Procfile
It defaults to one per core, but our dyno has 8 cores and 8 processes use too much memory
> Change celery concurrency to max 2 processes

- chat/models.py
- chat/tests.py
Fix buggy behavior where a solved puzzle channels would be moved to their meta's category from archive category.
> do not change puzzle category if solved

- api/tests.py
- google_api_lib/tasks.py
Fixes #590 
For some reason, `add_puzzle_link_to_sheet` was not called during puzzle creation, and only being called when puzzle's URL changed.
> add puzzle links to sheet at creation

- google_api_lib/tasks.py
Asks new owner for permission before transferring. 
It seems that this does not send an "Invitation to own" email as it would if the transfer was done through the normal Google drive UI.  Instead, you can see all the sheets with pending transfers by searching `pendingowner:me` or https://drive.google.com/drive/u/1/search?q=pendingowner:me. Then, select all, click "Share" and click "Accept Ownership?"
There's no longer need to do this mid-hunt, since the new named functions can be run even if it is owned by service account. We can do this after the hunt to make sure the sheets are owned by a normal account (not a huge deal if we don't, just prevents the sheets from being lost into the abyss if we ever get rid of the service account).
> fix iss #616: pending owner

- hunts/src/NameCell.js
- hunts/src/collapsedPuzzlesSlice.js
- hunts/src/puzzle-table.js
- hunts/src/store.js
We have a utility reflecting sections of our redux state into local storage. This PR adds a slice that tracks which puzzles are collapsed and preloads react-table with that information.
https://github.com/cardinalitypuzzles/cardboard/issues/607
> Keep collapsed puzzles in local storage

- hunts/src/NameCell.js
Before, for reference
fixes https://github.com/cardinalitypuzzles/cardboard/issues/597
> use better chevrons for the expansion toggle

- puzzles/puzzle_tag.py
Old code was doing a separate db query for each `get_or_create` on each default tag.
> improve performance of default puzzle tag population

- cardboard/context_processors.py
- cardboard/settings.py
- cardboard/templates/base.html
- cardboard/templates/home.html
- cardboard/templates/privacy.html
- cardboard/templates/reactbase.html
- hunts/src/SiteHeader.js
- new-hunt-setup.md
(Continuing to upstream my local diffs.)
When I set up a site for my team, it felt wrong to keep the "Cardinality" branding. If you agree, here's an attempt to make the branding configurable. I've kept the defaults unchanged, so there should be no visible changes unless you set the appropriate env variables.
> Adds settings variables to control app branding.

- chat/models.py
- chat/tasks.py
- discord_lib/discord_chat_service.py
Celery job to clean up solved puzzle's channels was broken because `get_text_channel_participants` had not been re-implemented
> fix discord channel cleanup

- hunts/src/AnswerCell.js
- hunts/src/NameCell.js
Addresses #667 and #280 by making the editing buttons appear only on hover. This significantly reduces the UI clutter.
https://github.com/cardinalitypuzzles/cardboard/assets/342514/bb3419f4-89c1-4104-87fb-470d634aadc7
> Display puzzle name and answer editing buttons on hover.

- hunts/forms.py
- hunts/templates/index.html
Fixes #406
Makes creating a hunt slightly easier, also cleaning up the form code
Before:
After:
> Switch to browser date and time pickers for hunt creation

- hunts/src/SubmitAnswerModal.js
Adds a backsolved checkbox option to the submit answer modal.
I know this is simple, but I have no idea what I'm doing, so any feedback would be appreciated.
Addresses #675 .
> add backsolved option to SubmitAnswerModal

- hunts/src/EditPuzzleTagsModal.js
- hunts/src/puzzlesSlice.js
> Add puzzle tag selector and merge puzzle + hunt tags.

- hunts/src/HuntViewHeader.js
Was thinking the header displaying overall hunt progress could be cleaned up a little -- lmk what you think.
old
new
> Simplify header puzzle stats

- cardboard/static/style.css
- hunts/src/AnswerCell.js
- hunts/src/StatusCell.js
The default Bootstrap button takes up a bit more vertical space than it needs to. This reclaims a little bit of it, for puzzles without long names and lots of tags (which should be most of them).
Could be argued that this makes the page look worse (happy to abandon), but I prefer it cause it's more compact + more of a 'Google spreadsheet' look.
(some of the puzzles take up more line height than you'd expect bc of the invisible wrench button)
**old**
**new**
> reduce line height of table buttons

- cardboard/static/style.css
`.bootstrap` isn't applied in dark mode apparently
> fix button compactness for dark mode

- app.json
- new-hunt-setup.md
Raised in #818, verified with our current live instance that the new heroku-provided buildpack just works.
> remove poetry buildpack from docs

- cardboard/settings.py
I was getting this error locally
```
celery-1  | [2024-12-25 04:35:59,412: ERROR/ForkPoolWorker-16] Task google_api_lib.tasks.update_active_users[1000ee76-95be-4f02-8e65-ca3c7d6efbdc] raised unexpected: TypeError("Connection.__init__() got an unexpected keyword argument 'ssl_cert_reqs'") 
```
I think because our Docker redis set up is not SSL enabled, but `ssl_cert_reqs` is needed for Heroku (#801)
> only set ssl_cert_reqs for TLS/SSL-enabled redis

- google_api_lib/tasks.py
This was previously because we used this for auth (so we treated link sharing on as a special case). Don't want this behavior now.
> Fix folder permissions check when link sharing is on

- hunts/src/AnswerCell.tsx
- hunts/src/TagCell.tsx
- add padding to answer column (regression from #846)
- never show a puzzle's own meta tag (only affects nested metas, they're already hidden for non-nested)
> two small UI fixes

- hunts/src/EditPuzzleModal.tsx
- hunts/src/EditPuzzleTagsModal.tsx
- hunts/src/NameCell.tsx
- hunts/src/TagCell.tsx
move 'tag' button to tags column, which is more intuitive.
i didn't bother to add hover behavior to the tag button because i'm planning to remove these icons altogether, but am splitting the commit up a bit.
almost all of this is just c/p between different files, the work was basically already done for me
move meta-parenting stuff to the puzzle edit modal and remove it from the tag modal
> menu cleanup #1: tagging in tags column, metas in name column

- hunts/src/puzzle-table.tsx
For years, the Links column has been quite far from the puzzle Name (first column) - see image below. Most Cardboard users browse the list of puzzles and use these links to open Sheets or original puzzles. So it'd be more useful to place these links closer to the puzzle Name.
After this change:
> Move Links column closer to Name

- hunts/src/NameCell.tsx
- hunts/src/NotesCell.tsx
- hunts/src/TagCell.tsx
this removes the icons entirely. instead, clickable cells will now highlight (with a yellow background) when hovered, indicating an action can be taken. (sorry idk how to take a video) (also sorry the bg is kinda ugly but it's harder to fix because of the `react-table` component we use)
- clicking on Name column opens up puzzle edit dialog
- clicking on Tags column opens up tag edit dialog
- clicking on the Notes column just turns the cell into an inline editable textbox instead of opening up a modal
resolves #835
> menu/UI cleanup #3: click-to-edit on some columns

- cardboard/static/style.css
- hunts/src/NameCell.tsx
- hunts/src/NotesCell.tsx
- hunts/src/TagCell.tsx
- hunts/src/TagPill.tsx
fixes from trigger-happy #851 merge:
- use `:hover` to control highlighted css
- clicking on tags filters by tag only and doesn't also open the tag window
> switch hoverable elements to use :hover

- hunts/src/AddPuzzleModal.tsx
- hunts/src/EditPuzzleModal.tsx
- hunts/src/NotesCell.tsx
Fix Notes cell bugs
The textarea was only taking up part of the width of the cell, and the
yellow hover background would still appear while you were editing the note
which was weird.
Re-order Edit Puzzle modal
This checkbox looked kinda bad underneath the meta tag section.
Change the ugly "Is meta" language
Hide the meta section when there are no metas to display
> Misc frontend tweaks & fixes

- hunts/src/NameCell.tsx
Think this interaction is a bit wonky/unintuitive. The interaction between this & metas appears especially problematic because clicking on a meta also toggles expand/collapse.
This also fixes a bug where puzzle indentation was lost.
> Revert clickable editing for the Name column
